<?php

// Quick script to mark enrollment as completed
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

$enrollmentId = $argv[1] ?? null;

if (! $enrollmentId) {
    echo "Usage: php fix-completion.php <enrollment_id>\n";
    exit(1);
}

$enrollment = App\Models\UserCourseEnrollment::with('course')->findOrFail($enrollmentId);
$chapters = $enrollment->course->chapters;

echo "Marking all chapters as completed for enrollment #{$enrollmentId}...\n";

foreach ($chapters as $chapter) {
    App\Models\UserCourseProgress::updateOrCreate(
        [
            'enrollment_id' => $enrollment->id,
            'chapter_id' => $chapter->id,
        ],
        [
            'is_completed' => true,
            'completed_at' => now(),
            'time_spent' => $chapter->duration ?? 60,
            'last_accessed_at' => now(),
        ]
    );
}

// Update enrollment
$totalChapters = $chapters->count();
$enrollment->update([
    'progress_percentage' => 100,
    'completed_at' => now(),
    'status' => 'completed',
]);

echo "✓ Enrollment marked as completed!\n";
echo "✓ Certificate will be auto-generated by observer\n";
echo "\nCheck: http://127.0.0.1:8000/admin/certificates\n";
