@extends('layouts.app')
@section('title', 'Florida Compliance Reports')
@section('content')
<div class="container-fluid py-4" style="margin-left: 300px; max-width: calc(100% - 320px); padding: 20px;">
    <h1 class="mb-4">Florida Compliance Reports</h1>
    
    <div class="card mb-4">
        <div class="card-header">
            <h5>Generate New Report</h5>
        </div>
        <div class="card-body">
            <form id="reportForm">
                <div class="row">
                    <div class="col-md-3">
                        <label>Report Type</label>
                        <select name="report_type" class="form-control" required>
                            <option value="school_activity">School Activity</option>
                            <option value="certificate_usage">Certificate Usage</option>
                            <option value="submission_errors">Submission Errors</option>
                            <option value="revenue">Revenue</option>
                        </select>
                    </div>
                    <div class="col-md-3">
                        <label>Start Date</label>
                        <input type="date" name="data_range_start" class="form-control" required>
                    </div>
                    <div class="col-md-3">
                        <label>End Date</label>
                        <input type="date" name="data_range_end" class="form-control" required>
                    </div>
                    <div class="col-md-3">
                        <label>&nbsp;</label>
                        <button type="submit" class="btn btn-primary d-block w-100">Generate Report</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h5>Generated Reports</h5>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Report Type</th>
                        <th>Date Range</th>
                        <th>Generated By</th>
                        <th>Generated At</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody id="reports-list"></tbody>
            </table>
        </div>
    </div>
</div>

<script>
document.getElementById('reportForm').addEventListener('submit', async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    
    const response = await fetch('/api/admin/florida-reports/generate', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
        },
        body: JSON.stringify(Object.fromEntries(formData))
    });
    
    if (response.ok) {
        alert('Report generated successfully');
        loadReports();
        e.target.reset();
    }
});

async function loadReports() {
    const response = await fetch('/api/admin/florida-reports');
    const data = await response.json();
    
    document.getElementById('reports-list').innerHTML = data.map(report => `
        <tr>
            <td>${report.report_type}</td>
            <td>${report.data_range_start} to ${report.data_range_end}</td>
            <td>${report.generated_by}</td>
            <td>${report.created_at}</td>
            <td>
                <a href="/api/admin/florida-reports/${report.id}/download" class="btn btn-sm btn-primary">Download</a>
            </td>
        </tr>
    `).join('');
}

loadReports();
</script>
@endsection
